apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001 # Change if needed; NodePort range is typically 30000-32767
